name                                        =   "nnbedevdil"
location                                    =   "West Europe"
environment                                 =   "DEV"   
costcenter                                  =   "CEBEL100"
ApplicationName                             =   "DIL"  