name                                        =   "nnbetstdil"
location                                    =   "West Europe"
environment                                 =   "Test"   
costcenter                                  =   "CEBEL100"
ApplicationName                             =   "DIL"  