name                                        =   "nnbe"
location                                    =   "West Europe"
environment                                 =   "PRD"   
costcenter                                  =   "CEBEL100"
application                                 =   "DIL"  
replication_type                            =   "LRS"
account_tier                                =   "Standard"
accountkind                                 =   "StorageV2"